#!/usr/bin/env node

const Cli = require('../lib/utils/Cli');
const Axgen = require('../lib/Axgen');

const commandParser = new Cli();
const app = new Axgen(commandParser);

const input = commandParser.processInput();

app.run(input.commands, input.parameter, input.flags)
  .then(() => {
  }).catch((reason) => {
    commandParser.logError(`\x1b[31mERROR!\x1b[0m ${reason.message}`, reason);
  });
